CREATE TABLE admin (
  id INT AUTO_INCREMENT PRIMARY KEY,
  admin VARCHAR(100) NOT NULL,
  password VARCHAR(200) NOT NULL
);

CREATE TABLE products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  image VARCHAR(100) NOT NULL,
  category VARCHAR(100) NOT NULL,
  price VARCHAR(100) NOT NULL,
  title VARCHAR(100) NOT NULL,
  description TEXT NOT NULL
);

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  username VARCHAR(100) NOT NULL,
  phone VARCHAR(100) NOT NULL,
  password TEXT NOT NULL,
  status VARCHAR(100) DEFAULT 'user'
);

CREATE TABLE cart (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL,
  product VARCHAR(100) NOT NULL
);

CREATE TABLE orders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  phone VARCHAR(100) NOT NULL,
  address TEXT NOT NULL,
  products TEXT NOT NULL,
  price VARCHAR(100) NOT NULL
);
